name: Publish

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Development Images
        run: docker build -t sindbadia/client -f ./client/Dockerfile.dev ./client
      - name: Run Tests
        run: docker run -e CI=true sindbadia/client yarn test

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build production images
        run: |
          docker build -t  ghcr.io/sindbadia/multi-client ./client &&
          docker build -t  ghcr.io/sindbadia/multi-nginx ./nginx &&
          docker build -t  ghcr.io/sindbadia/multi-server ./server &&
          docker build -t  ghcr.io/sindbadia/multi-worker ./worker
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Container Registry
        run: |
          docker push ghcr.io/sindbadia/multi-client &&
          docker push ghcr.io/sindbadia/multi-nginx &&
          docker push ghcr.io/sindbadia/multi-server &&
          docker push ghcr.io/sindbadia/multi-worker
